### ISSUE TITLE
Duplicate history trends

### ISSUE THREAD

**Issue by apulverizer** [fescobar/allure-docker-service#110]
It seems like the history trend is invalid. 

Here is a simple repro case using the sample data:
1. In the `allure-api-usage` directory call `python send_results.py`
2. In the hosted api run `generate-report` on the `default` project

After a single test run I'm seeing a trend chart like:
<img width=300 src="https://user-images.githubusercontent.com/2099642/88568984-cbc11a80-d007-11ea-90ec-62d1bd25c94e.png"/>

Notice there are two entries for `#1` this seems invalid.

Running `allure server allure-results-example/` locally renders it like:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/2099642/88569478-7c2f1e80-d008-11ea-93af-ab7bc55f8695.png">
which is what I expect to see.

It seems like the history is getting duplicated somehow.

Logs:
```
Starting reporting_allure_1 ... done
Attaching to reporting_allure_1
allure_1  | Not checking results automatically
allure_1  | ALLURE_VERSION: 2.13.4
allure_1  | Generating default report
allure_1  | ls: cannot access '/app/allure-docker-api/static/projects/default/reports': No such file or directory
allure_1  | Creating results directory for PROJECT_ID: default
allure_1  | Creating executor.json for PROJECT_ID: default
allure_1  | Generating report for PROJECT_ID: default
allure_1  | Report successfully generated to /app/allure-docker-api/static/projects/default/reports/latest
allure_1  | Status: 200
allure_1  | 2020-07-27 17:27:33.819:INFO::main: Logging initialized @699ms to org.eclipse.jetty.util.log.StdErrLog
allure_1  | Creating history on results directory for PROJECT_ID: default ...
allure_1  | Copying history from previous results...
allure_1  | Status: 200
```

This is my compose file:
```yml
version: '3'
services:
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: "TRUE"
      KEEP_HISTORY_LATEST: 25
    ports:
      - "5050:5050"
    volumes:
      - ${PWD}/projects:/app/projects
```
