### ISSUE TITLE
False test count

### ISSUE THREAD

**Issue by AdamRussak** [fescobar/allure-docker-service#145]
our test count is off,
as you can see in the picture below the test count is 65, but we have only 33 tests.

the tests are running on windows and uploaded using the python script in your repo.

i cant really understand why this is happening.

here is the docker-compose:
```
version: '3'
services:
  allure:
    container_name: "allure_server-prod"
    image: "frankescobar/allure-docker-service:latest"
    restart: always
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 25
      EMAILABLE_REPORT_TITLE: "Allure Report"
      SERVER_URL: "http://<url>:5050"
    ports:
      - "5050:5050"
    volumes:
      - /home/builder/allure/projects:/app/projects
    networks:
      - allure_bridge
```

![image](https://user-images.githubusercontent.com/31593022/103473787-317ab500-4da5-11eb-820d-49054dbe09f4.png)

**Comment by fescobar** [comment]
@AdamRussak disable automatic results and use the API to generate the report.

```sh
environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
```
```sh
GET /generate-report
```

**Comment by AdamRussak** [comment]
i am doing it this why, you can see the yaml here:
```
environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
```

and the API call:

```
# Invoke-WebRequest -Method Get -Uri "http://<url>:5050/allure-docker-service/clean-results?project_id=<project>" -Headers @{ "accept" = "*/*"} -UseBasicParsing
          # start-sleep 5
          Invoke-WebRequest -Method Get -Uri "http://<url>:5050/allure-docker-service/generate-report?project_id=<project>" -Headers @{ "accept" = "*/*"} -UseBasicParsing
```

**Comment by fescobar** [comment]
@AdamRussak you need to use the POST /send-results before generating the report.

**Comment by AdamRussak** [comment]
I'm sending them using the python script...is it different?

**Comment by fescobar** [comment]
@AdamRussak It's  the same, the important thing is the right order 
1. Run Tests
2. Send Results (API)
3. Generate Report (API)

**Comment by AdamRussak** [comment]
That's exactly what I am doing...

**Comment by fescobar** [comment]
@AdamRussak  You need to do that at the end of all executions, don't do that per test.

**Comment by kormachevt** [comment]
Greetings! Have the same issue. 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: allure-config-map
  namespace: allure-docker-service
data:
  CHECK_RESULTS_EVERY_SECONDS: NONE
  KEEP_HISTORY: "1"
  URL_PREFIX: "/allure-api"
  TLS: "1"
  SECURITY_ENABLED: "1"
  MAKE_VIEWER_ENDPOINTS_PUBLIC: "0"

```
I am sending results via your provided example of shell script. 

Steps:
1. Generate results for 10 tests
2. Send them via sh script (with generate report call uncommented)
3. gradle clean
4. Generate results with 20 different tests
5. Send them via sh script (with generate report call uncommented)

Result: Allure UI shows me for latest report that the was total 30 cases, I am able to see results for first 10 tests, although they were not second run test suite. 
Also I have the same odd combined time (one time it was 2 days).
