### ISSUE TITLE
ebs volume unusual disk usage

### ISSUE THREAD

**Issue by rust84** [fescobar/allure-docker-service#164]
We are hosting allure docker service in kubernetes deployed with the example yamls. We have 33 projects in total with automatic scanning disabled. A report is generated each night and they are around 100M each. 

What is strange is we are getting out of disk space errors when the volume does not appear to be getting full. So far I've had to increase the size of the volume twice when the reported disk usage is less than 100% and this has resolved them not being able to upload new reports. 

```
{'message': \"[Errno 28] No space left on device: '/app/allure-docker-api/static/projects/ac-bdd-testing-custom/results/f295abaa-b380-4e2b-90c6-9471a48411a8-attachment.txt'\", 'file_name': 'f295abaa-b380-4e2b-90c6-9471a48411a8-attachment.txt'}
```
```
allure@allure-deployment-97bd8f6d7-9zmbf:/app$ fallocate -l 50M /app/allure-docker-api/static/projects/deleteme
fallocate: cannot open /app/allure-docker-api/static/projects/deleteme: No space left on device
```

Disk usage according to the container

```
/dev/nvme2n1     30G   18G   13G  59% /app/allure-docker-api/static/projects
```

Restarting the pod doesn't free up the space so I am not sure what is consuming it. I have enabled the storage optimization experimental feature and this has reduced the size of the reports. It remains to be seen if this hidden usage will keep growing over time. Increasing the volume size seems to have resolved it for now. Any idea what could be causing it? Is this expected behaviour?

Deployment

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: allure-deployment
  namespace: allure-docker-service
spec:
  template:
    metadata:
      name: allure-container
      labels:
        type: app
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: allure
          image: 'frankescobar/allure-docker-service:2.13.8'
          imagePullPolicy: Always
          ports:
            - containerPort: 5050
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          envFrom:
            - configMapRef:
                name: allure-config-map
            - secretRef:
                name: allure-secret
          volumeMounts:
            - name: reports-volume
              mountPath: /app/projects
        - name: allure-ui
          image: 'frankescobar/allure-docker-service-ui:7.0.3'
          imagePullPolicy: Always
          ports:
            - containerPort: 5252
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          envFrom:
            - configMapRef:
                name: allure-config-ui-map
      volumes:
        - name: reports-volume
          persistentVolumeClaim:
            claimName: allure-persistent-volume-claim
  replicas: 1
  selector:
    matchLabels:
      type: app
```

PVC

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: allure-persistent-volume-claim
  namespace: allure-docker-service
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
```
