### ISSUE TITLE
Jira and Allure integration - how to display only the final status result?

### ISSUE THREAD

**Issue by brunoklein** [fescobar/allure-docker-service#213]
Dear allure-docker-service community,

How could we configure the Allure report on Jira to not display the failed attempts in the final report?
Currently the report is quantifying all failures, even for the scenarios that failed once but passed due a retry.

Current report on Jira,
showing +1 failure - this scenario failed once before pass:

<img width="957" alt="image" src="https://user-images.githubusercontent.com/6807173/218775839-c5583d68-206c-4bdb-ac56-d23df8637c05.png">

Same report on Jenkins Allure report,
as expected, showing no failures in the final result

<img width="737" alt="image" src="https://user-images.githubusercontent.com/6807173/218778893-4e85f9b4-1c84-4bdc-bc5c-85c811e80691.png">

In my case it would be also acceptable if we could display only the final result on Jira (PASSED or FAILED) instead of the amount of scenarios. The current situation is always requiring us to access the report on Jenkins to confirm the final result.

This is the command I'm running on my Jenkins pipeline in order to send the allure status report to Jira:

docker-compose.yaml

```
version: '3.7'

services:
  allure:
    image: frankescobar/allure-docker-service
    user: ${CURRENT_USER:-0}
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 1
    volumes:
      - ./output/allure:/tmp:rw
```

run command

```
docker-compose up && docker-compose exec -T allure sh -c "\
    	export \
    		ALLURE_JIRA_ENABLED='true' \
    		ALLURE_JIRA_ENDPOINT='jira.mycompany.com' \
    		ALLURE_JIRA_LAUNCH_ISSUES='TA-1234' \
    		ALLURE_JIRA_USERNAME='myJiraUsername' \
    	        ALLURE_JIRA_PASSWORD='myJiraPassword'; \
	        allure generate /tmp -o /tmp/allure-report --clean"
```

Output

```
[JiraExportResult(issueKey=TA-1234, externalId=Allure E2E Test Report - env:staging suite:(?=.*@regression)^((?!.*@staging-skip)(?!.*@disabled)(?!.*@spa-regression)) build:396, status=ok, message=null)]
```
