### ISSUE TITLE
Incorrect merging results on Trend

### ISSUE THREAD

**Issue by QA-automation-engineer** [fescobar/allure-docker-service#222]
Hi @fescobar 
I faced some strange behavior of `allure-docker-service`.
I launched `allure-docker-service` through docker-compose with the following ens vars:
```yaml
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 1
      KEEP_HISTORY_LATEST: 5
```
Actually, I uploaded several results onto `allure-docker-service` and generated report for each result.
Now I see the following in the last report and Trend shows me that both the 1st and the 2nd runs have 107 TCs:
![image](https://github.com/fescobar/allure-docker-service/assets/17032203/74d7f738-7cb5-4b3d-a74c-141686276e53)
But the 2nd run has only 42 TCs launched if I launch allure report locally:
![image](https://github.com/fescobar/allure-docker-service/assets/17032203/afee7a2f-a7d3-4383-9556-02e2a597beac)
Looks like that TCs that weren't launched in the 2nd run was marked as passed somehow.

IMHO: Trend should show me different number of TCs 107 TCs for the 1st run and 42 for the 2nd run.
