### ISSUE TITLE
Copy allure-report/history in allure-results before generation, for allure trends to work?

### ISSUE THREAD

**Issue by anrock1985** [fescobar/allure-docker-service#28]
Hi, it is possible?

**Comment by fescobar** [comment]
@anrock1985 
Can you try with `beta` version, please?
Enable `KEEP_HISTORY` environment variable like in the example.
```
version: '3'
services:
  allure:
    image: "frankescobar/allure-docker-service:beta"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: "TRUE"
    ports:
      - "4040:4040"
      - "5050:5050"
    volumes:
      - ${PWD}/allure-results:/app/allure-results
```
![image](https://user-images.githubusercontent.com/1236418/61809825-f1847400-ae35-11e9-8e0d-c2eff2568a20.png)
![image](https://user-images.githubusercontent.com/1236418/61809841-f9dcaf00-ae35-11e9-857a-50670128c60c.png)




Let me know if it's working as you expected.
