### ISSUE TITLE
Every 10 seconds >> allure_1 | 127.0.0.1 - - [09/Jun/2020 21:39:47] "GET / HTTP/1.1" 200 -

### ISSUE THREAD

**Issue by dE1l** [fescobar/allure-docker-service#82]
Every 10 sends i see in docker logs this massage:
```
allure_1                    | 127.0.0.1 - - [09/Jun/2020 21:39:27] "GET / HTTP/1.1" 200 -
allure_1                    | 127.0.0.1 - - [09/Jun/2020 21:39:37] "GET / HTTP/1.1" 200 -
allure_1                    | 127.0.0.1 - - [09/Jun/2020 21:39:47] "GET / HTTP/1.1" 200 -
allure_1                    | 127.0.0.1 - - [09/Jun/2020 21:39:57] "GET / HTTP/1.1" 200 -
allure_1                    | 127.0.0.1 - - [09/Jun/2020 21:40:07] "GET / HTTP/1.1" 200 -
```
Му docker-compose config:
```
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: "TRUE"
      KEEP_HISTORY_LATEST: 20
      SERVER_URL: "http://localhost:5050/latest-report"
    ports:
      - "5050:5050"
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-reports:/app/default-reports
```

That is this? How i can switch off this message?
